CONFIGURED = "configured"
USERNAME = "username"
PASSWORD = "password"
LOGGED_IN = "logged_in"
LAST_LOGIN = "last_login"
TOKEN = "token"
UID = "uid"
REFRESH_TOKEN="refresh_token"
REBUILD_EPG="rebuild_epg"
CONFIGURE_EPG="configure_epg"
LAST_EPG="last_epg"
# navigation
SHOW_LIVE_CHANNELS="show_live_channels"
SHOW_SERIES="show_series"
PLAY_STREAM="play_stream"